// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: country.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateCountryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ip             string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	ValidCountries []string               `protobuf:"bytes,2,rep,name=validCountries,proto3" json:"validCountries,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateCountryRequest) Reset() {
	*x = ValidateCountryRequest{}
	mi := &file_country_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCountryRequest) ProtoMessage() {}

func (x *ValidateCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_country_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCountryRequest.ProtoReflect.Descriptor instead.
func (*ValidateCountryRequest) Descriptor() ([]byte, []int) {
	return file_country_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateCountryRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ValidateCountryRequest) GetValidCountries() []string {
	if x != nil {
		return x.ValidCountries
	}
	return nil
}

type ValidateCountryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	CountryName   string                 `protobuf:"bytes,2,opt,name=countryName,proto3" json:"countryName,omitempty"`
	IsValid       bool                   `protobuf:"varint,3,opt,name=isValid,proto3" json:"isValid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCountryResponse) Reset() {
	*x = ValidateCountryResponse{}
	mi := &file_country_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCountryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCountryResponse) ProtoMessage() {}

func (x *ValidateCountryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_country_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCountryResponse.ProtoReflect.Descriptor instead.
func (*ValidateCountryResponse) Descriptor() ([]byte, []int) {
	return file_country_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateCountryResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ValidateCountryResponse) GetCountryName() string {
	if x != nil {
		return x.CountryName
	}
	return ""
}

func (x *ValidateCountryResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_country_proto protoreflect.FileDescriptor

const file_country_proto_rawDesc = "" +
	"\n" +
	"\rcountry.proto\x1a\x1cgoogle/api/annotations.proto\"P\n" +
	"\x16ValidateCountryRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12&\n" +
	"\x0evalidCountries\x18\x02 \x03(\tR\x0evalidCountries\"e\n" +
	"\x17ValidateCountryResponse\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12 \n" +
	"\vcountryName\x18\x02 \x01(\tR\vcountryName\x12\x18\n" +
	"\aisValid\x18\x03 \x01(\bR\aisValid2u\n" +
	"\aCountry\x12j\n" +
	"\x13ValidateCountryByIP\x12\x17.ValidateCountryRequest\x1a\x18.ValidateCountryResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/country/validateB\x06Z\x04./pbb\x06proto3"

var (
	file_country_proto_rawDescOnce sync.Once
	file_country_proto_rawDescData []byte
)

func file_country_proto_rawDescGZIP() []byte {
	file_country_proto_rawDescOnce.Do(func() {
		file_country_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_country_proto_rawDesc), len(file_country_proto_rawDesc)))
	})
	return file_country_proto_rawDescData
}

var file_country_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_country_proto_goTypes = []any{
	(*ValidateCountryRequest)(nil),  // 0: ValidateCountryRequest
	(*ValidateCountryResponse)(nil), // 1: ValidateCountryResponse
}
var file_country_proto_depIdxs = []int32{
	0, // 0: Country.ValidateCountryByIP:input_type -> ValidateCountryRequest
	1, // 1: Country.ValidateCountryByIP:output_type -> ValidateCountryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_country_proto_init() }
func file_country_proto_init() {
	if File_country_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_country_proto_rawDesc), len(file_country_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_country_proto_goTypes,
		DependencyIndexes: file_country_proto_depIdxs,
		MessageInfos:      file_country_proto_msgTypes,
	}.Build()
	File_country_proto = out.File
	file_country_proto_goTypes = nil
	file_country_proto_depIdxs = nil
}
